### ISSUE TITLE
package-lock.json

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [dword-design/base#340]
Could you provide a `package-lock.json`?

**Comment by dword-design** [comment]
@Alessandro-Barbieri hmm I think it will lead to sync issues between `package-lock.json` and `yarn.lock`. As far as I see it, most projects I know provide the one or the other, and depending on the provided one, you use `npm` or `yarn`.

Also see https://www.reddit.com/r/javascript/comments/976dxy/i_have_both_yarn_and_npm_installed_and_theyre.

**Comment by Alessandro-Barbieri** [comment]
ok, I see
